blueprint:
  name: Moes/Tuya 2-Button Scene Switch (TS0044)
  description: >
    Controls various entities based on single and double press actions from a Moes 2-Button Scene Switch.
  domain: automation
  input:
    switch_topic:
      name: MQTT Topic
      description: The MQTT topic for the scene switch.
      selector:
        text:
    single_1:
      name: Action for 1 Single Press
      description: Action to run when button 1 is single pressed.
      selector:
        action: {}
    single_2:
      name: Action for 2 Single Press
      description: Action to run when button 2 is single pressed.
      selector:
        action: {}
    double_1:
      name: Action for 1 Double Press
      description: Action to run when button 1 is double pressed.
      selector:
        action: {}
    double_2:
      name: Action for 2 Double Press
      description: Action to run when button 2 is double pressed.
      selector:
        action: {}
    hold_1:
      name: Action for 1 hold Press
      description: Action to run when button 1 is held.
      selector:
        action: {}
    hold_2:
      name: Action for 2 hold Press
      description: Action to run when button 2 is held.
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: !input switch_topic

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence: !input single_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence: !input single_2

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_double' }}"
        sequence: !input double_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_double' }}"
        sequence: !input double_2

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_hold' }}"
        sequence: !input hold_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_hold' }}"
        sequence: !input hold_2

mode: single
